#! /bin/sh
### BEGIN INIT INFO
# Provides:          kwapi
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 5
# Default-Stop:      0 6
# short-description: configure kwapi to monitor energy on sites
# Description: energy monitoring, RRD, live visualization, long-term storage, ganglia
### END INIT INFO

# Author: Laurent Pouilloux
#
PREFIX=/usr/local/bin/
DESC="Energy monitoring service"
NAME=kwapi
SCRIPTNAME=/etc/init.d/kwapi
USER=kwapi


# Create required directories
[ -d /var/log/kwapi ] || mkdir -p /var/log/kwapi
[ -d /var/lib/kwapi ] || mkdir -p /var/lib/kwapi
# Give permissions to $USER
#chown -R $USER:$USER /var/log/kwapi
#chown -R $USER:$USER /var/lib/kwapi


# Read configuration
if [ -r /etc/kwapi/daemon.conf ]; then
    . /etc/kwapi/daemon.conf
else
    echo 'Unable to read configuration file, abort ..'
    exit 1
fi

elements="DRIVERS FORWARDER API RRD HDF5"

for element in $elements
do
    toto=`echo $element`
    echo $(`echo $element`)
    
done

exit 

daemon_start () {
    name=$1
    echo "Starting ${name}"
    PID=$(pid_element $name)
    start-stop-daemon --start --make-pidfile --pidfile $PID --exec ${PREFIX}$name --chuid $USER --background
}

pid_element () {
    echo /var/run/$1.pid
}

if $DRIVERS; then    
    daemon_start kwapi-drivers 
fi

exit 


exit


echo $PLUGINS
exit


exit


PID_DRIVERS="/var/run/kwapi-drivers.pid"
PID_FORWARDER="/var/run/kwapi-forwarder.pid"
PID_API="/var/run/kwapi-api.pid"
PID_RRD="/var/run/kwapi-rrd.pid"
PID_HDF5="/var/run/kwapi-hdf5.pid"





# Read configuration
if [ -r /etc/kwapi/daemon.conf ]; then
    . /etc/kwapi/daemon.conf
else
    echo 'Unable to read configuration file, abort ..'
    exit 1
fi


env
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    if $DRIVERS; then
        echo "Starting kwapi-drivers"
        start-stop-daemon --start --make-pidfile --pidfile $PID_DRIVERS --exec ${PREFIX}kwapi-drivers --chuid $USER --background
    fi
    if $FORWARDER; then
        echo "Starting kwapi-forwarder"
        start-stop-daemon --start --make-pidfile --pidfile $PID_FORWARDER --exec ${PREFIX}kwapi-forwarder --chuid $USER --background
    fi
    if $API; then
        echo "Starting kwapi-api"
        start-stop-daemon --start --make-pidfile --pidfile $PID_API --exec ${PREFIX}kwapi-api --chuid $USER --background
    fi
    if $RRD; then
        echo "Starting kwapi-rrd"
        start-stop-daemon --start --make-pidfile --pidfile $PID_RRD --exec ${PREFIX}kwapi-rrd --chuid $USER --background
    fi
    if $HDF5; then
        echo "Starting kwapi-hdf5"
        start-stop-daemon --start --make-pidfile --pidfile $PID_HDF5 --exec ${PREFIX}kwapi-hdf5 --chuid $USER --background 
    fi
    ;;
  stop)
    if [ -f $PID_DRIVERS ]; then
        echo "Stopping kwapi-drivers"
        start-stop-daemon --stop --pidfile $PID_DRIVERS
    fi
    if [ -f $PID_FORWARDER ]; then
        echo "Stopping kwapi-forwarder"
        start-stop-daemon --stop --pidfile $PID_FORWARDER
    fi
    if [ -f $PID_API ]; then
        echo "Stopping kwapi-api"
        start-stop-daemon --stop --pidfile $PID_API
    fi
    if [ -f $PID_RRD ]; then
        echo "Stopping kwapi-rrd"
        start-stop-daemon --stop --pidfile $PID_RRD
    fi
    if [ -f $PID_HDF5 ]; then
        echo "Stopping kwapi-hdf5"
        start-stop-daemon --stop --pidfile $PID_HDF5
    fi
    ;;
  restart)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: /etc/init.d/kwapi {start|stop}"
    exit 1
    ;;
esac

exit 0