#!/bin/bash
### BEGIN INIT INFO
# Provides:          kwapi
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 5
# Default-Stop:      0 6
# short-description: configure kwapi to monitor energy on sites
# Description: energy monitoring, RRD, live visualization, long-term storage, ganglia
### END INIT INFO

# Author: Laurent Pouilloux, François Rossigneux
#
PREFIX=/usr/local/bin/
DESC="Energy monitoring service"
NAME=kwapi
SCRIPTNAME=/etc/init.d/kwapi
USER=kwapi

# Create required directories
[ -d /var/log/kwapi ] || mkdir -p /var/log/kwapi
[ -d /var/lib/kwapi ] || mkdir -p /var/lib/kwapi

# Give permissions to $USER
chown -R $USER:$USER /var/log/kwapi /var/lib/kwapi

# Read configuration
if [ -r /etc/kwapi/daemon.conf ]; then
    . /etc/kwapi/daemon.conf
    kwapi_elements=`compgen -A variable | grep KWAPI`
else
    echo 'Unable to read configuration file, abort ..'
    exit 1
fi

pid_element () {
    echo /var/run/$1.pid
}

daemon_start () {
    EXEC=${1//_/-}
    echo "Starting ${EXEC,,}"
    PID=$(pid_element $1)
    start-stop-daemon --start --make-pidfile --pidfile $PID --exec ${PREFIX}${EXEC,,} --chuid $USER --background
}

daemon_stop () {
    EXEC=${1//_/-}
    echo "Stopping ${EXEC,,}"
    PID=$(pid_element $1)
    start-stop-daemon --stop --pidfile $PID
}

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    for element in $kwapi_elements
    do
        if eval "$"$element; then
            daemon_start $element  
        fi
    done
    ;;
  stop)
    for element in $kwapi_elements
    do
        if eval "$"$element; then
            daemon_stop $element
        fi  
    done
    ;;
  restart)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: /etc/init.d/kwapi {start|stop|restart}"
    exit 1
    ;;
esac

exit 0